### ISSUE TITLE
Improve threaded pool functions

### ISSUE THREAD

**Issue by ByteOfDestiny** [QSmally/QDB#19]
I experienced a bugs while testing out pools which run on a thread and I think it should be changed. Because yes, there are functions like set fetch and erase, but you might wanna manage cache and it’s weird with the query function

Because if the property returns a function itll execute that function so I think it’s best to wrap all functions of connection in the gateway class.

**Comment by QSmally** [comment]
Honestly, I was thinking on reworking it as well. Thanks for initiating this issue!

**Comment by ByteOfDestiny** [comment]
Np, I thought that you could like make some type of function provider? Or extend the gateway class from some provider otherwise the gateway would be cluttered with functions that do the same thing but that’s up to the codebase really

Is there maybe an automated way to get function/property names of the class and get them onto gateways reliably?

**Comment by QSmally** [comment]
I guess there's something I can try using `Gateway.prototype[name]` that sends it off to the queue, no?

**Comment by QSmally** [comment]
This has been implemented on master, specifically commit [b8fac5a](https://github.com/QSmally/QDB/commit/b8fac5a21121e4b24dcaa0d9c82da5a24bfcaf95). I'll be working on a better solution in the future
